version: "3.8"
services:
    my-dotnet-app:
        build:
            context: .
            dockerfile: Dockerfile.production # Use the production Dockerfile
        ports:
            - "8080:80" # Map container port 80 to host port 8080 (adjust as needed).
        environment:
            - ConnectionStrings__SqlDatabase=localhost,1433;Database=SportStore;Trusted_Connection=True;
