services:
    server:
        build:
            context: .
            target: final-env
        ports:
            - 8080:80
        environment:
            DOTNET_ConnectionStrings__SqlDatabase: "Server=localhost,1433;Database=SportStore;Trusted_Connection=True;"
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "Devopsg05!"
        ports:
            - "1433:1433"
