version: "3.8"
services:
    sportstore:
        image: docker.io/library/sportstoreapp
        build:
            context: .
            dockerfile: Dockerfile
        container_name: p3ops-demo-app-sportstore-services
        ports:
            - "8080:80"
        environment:
            - DOTNET_ENVIRONMENT=Production
            - DOTNET_ConnectionStrings__SqlDatabase=Server=sqlserver,1433;Database=SportStore;Trusted_Connection=True;
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Devopsg05!
        ports:
            - "1433:1433"
