version: "3.8"
services:
    server:
        build:
            context: .
            target: final-env
        ports:
            - 8080:80
        environment:
            DOTNET_ConnectionStrings__SqlDatabase: "Server=db;Database=myDataBase;User ID=sa;Password=example_123;"
    db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "example_123"
        ports:
            - "1433:1433"
