version: "3.8"
services:
    SportStore:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sportstore_container
        ports:
            - "8080:80"
        environment:
            - DOTNET_ENVIRONMENT=Production
            - DOTNET_ConnectionStrings__SqlDatabase=Server=sqlserver;Database=SportStore;User Id=SA;Password=Devopsg05!;MultipleActiveResultSets=true;
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Devopsg05!
        ports:
            - "1433:1433"
