version: '3.8'
services:
  my-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      MY_APP_DB_CONNECTION: "Server=localhost,1433;Database=SportStore;Trusted_Connection=True;"
  my-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "mysecretpassword"
    ports:
     - "1433:1433"

